{
    'name': 'Odoo 19 Accounting Module Report',
    'version': '19.0.1.0.0',
    'category': 'Accounting',
    'summary': 'Custom PDF Vendor Bill Report',
    'description': 'Generates specialized PDF layouts for vendor bills.',
    'sequence': 10,
    'author': 'Athraa Abd Alzahra',
    'license': 'LGPL-3',
    'company': 'Integrated Path',
    'maintainer': 'Integrated Path',
    'support': '',
    'website': '',
    'depends': ['base','account'],
    'data': [
        'security/ir.model.access.csv',
        'views/report_template.xml',
        'reports/accounting_report_view.xml',
        'reports/report_vendor_bill_custom.xml',
        'wizard/accounting_report_wizard_views.xml',
    ],
    'installable': True,
    'application': True,
}
